import { Lesson, StudentTask, UserProfile, BadgeItem } from '../types';
import { getTodayDateString } from './formatters';

export const PRESET_AVATARS = [
  { id: 'student-m', emoji: '🎓', title: 'طالب متميز', titleAr: 'طالب متميز', titleEn: 'Top Student' },
  { id: 'student-f', emoji: '👩‍🎓', title: 'طالبة متفوقة', titleAr: 'طالبة متفوقة', titleEn: 'Honor Student' },
  { id: 'rocket', emoji: '🚀', title: 'همّة عالية', titleAr: 'همّة عالية', titleEn: 'High Ambition' },
  { id: 'brain', emoji: '🧠', title: 'تركيز وذكاء', titleAr: 'تركيز وذكاء', titleEn: 'Deep Focus' },
  { id: 'doctor', emoji: '🩺', title: 'مسار صحي وطبي', titleAr: 'مسار صحي وطبي', titleEn: 'Pre-Med / Health' },
  { id: 'tech', emoji: '💻', title: 'تكنولوجيا وبرمجة', titleAr: 'تكنولوجيا وبرمجة', titleEn: 'CS & Tech' },
  { id: 'science', emoji: '🔬', title: 'علوم واستكشاف', titleAr: 'علوم واستكشاف', titleEn: 'Pure Science' },
  { id: 'engineer', emoji: '📐', title: 'هندسة ورياضيات', titleAr: 'هندسة ورياضيات', titleEn: 'Engineering' },
  { id: 'book', emoji: '📚', title: 'محب القراءة', titleAr: 'محب القراءة', titleEn: 'Bookworm' },
  { id: 'star', emoji: '🌟', title: 'نجم الدفعة', titleAr: 'نجم الدفعة', titleEn: 'Valedictorian' },
  { id: 'fire', emoji: '🔥', title: 'شغف وإصرار', titleAr: 'شغف وإصرار', titleEn: 'Unstoppable' },
  { id: 'palestine', emoji: '🇵🇸', title: 'شعار أنيق', titleAr: 'شعار أنيق', titleEn: 'Inspirational' },
];

export const ACADEMIC_STAGES = [
  { 
    id: 'college', 
    title: '🏫 مرحلة جامعية / معهد عالي', 
    titleAr: '🏫 مرحلة جامعية / معهد عالي', 
    titleEn: '🏫 University / College',
    emoji: '🏫', 
    grades: ['السنة الأولى', 'السنة الثانية', 'السنة الثالثة', 'السنة الرابعة', 'سنة التخرج 🎓'],
    gradesAr: ['السنة الأولى', 'السنة الثانية', 'السنة الثالثة', 'السنة الرابعة', 'سنة التخرج 🎓'],
    gradesEn: ['1st Year (Freshman)', '2nd Year (Sophomore)', '3rd Year (Junior)', '4th Year (Senior)', 'Graduation Year 🎓']
  },
  { 
    id: 'highschool', 
    title: '🎒 الثانوية العامة / الأزهرية 🇪🇬', 
    titleAr: '🎒 الثانوية العامة / الأزهرية 🇪🇬', 
    titleEn: '🎒 High School / Thanawya 🇪🇬',
    emoji: '🎒', 
    grades: ['1 ثانوي', '2 ثانوي', '3 ثانوي - علمي علوم 🔬', '3 ثانوي - علمي رياضة 📐', '3 ثانوي - أدبي 📚'],
    gradesAr: ['1 ثانوي', '2 ثانوي', '3 ثانوي - علمي علوم 🔬', '3 ثانوي - علمي رياضة 📐', '3 ثانوي - أدبي 📚'],
    gradesEn: ['10th Grade (1st Sec)', '11th Grade (2nd Sec)', '12th Grade (Science/Bio) 🔬', '12th Grade (Math/Eng) 📐', '12th Grade (Humanities) 📚']
  },
  { 
    id: 'bac', 
    title: '📜 البكالوريا المصرية الجديدة 🔥', 
    titleAr: '📜 البكالوريا المصرية الجديدة 🔥', 
    titleEn: '📜 Egyptian Baccalaureate 🔥',
    emoji: '📜', 
    grades: ['مسار الطب وعلوم الحياة 🩺', 'مسار الهندسة وعلوم الحاسب 💻', 'مسار الأعمال 💼', 'مسار الآداب والفنون 📜'],
    gradesAr: ['مسار الطب وعلوم الحياة 🩺', 'مسار الهندسة وعلوم الحاسب 💻', 'مسار الأعمال 💼', 'مسار الآداب والفنون 📜'],
    gradesEn: ['Pre-Med & Life Sciences 🩺', 'Engineering & CS Track 💻', 'Business & Commerce Track 💼', 'Arts & Humanities Track 📜']
  },
  { 
    id: 'prep', 
    title: '📖 المرحلة الإعدادية', 
    titleAr: '📖 المرحلة الإعدادية', 
    titleEn: '📖 Middle / Prep School',
    emoji: '📖', 
    grades: ['1 إعدادي', '2 إعدادي', '3 إعدادي'],
    gradesAr: ['1 إعدادي', '2 إعدادي', '3 إعدادي'],
    gradesEn: ['7th Grade (1st Prep)', '8th Grade (2nd Prep)', '9th Grade (3rd Prep)']
  },
  { 
    id: 'postgrad', 
    title: '🎓 دراسات عليا / ماجستير', 
    titleAr: '🎓 دراسات عليا / ماجستير', 
    titleEn: '🎓 Postgraduate / Masters / PhD',
    emoji: '🎓', 
    grades: ['تمهيدي ماجستير', 'ماجستير', 'دكتوراه'],
    gradesAr: ['تمهيدي ماجستير', 'ماجستير', 'دكتوراه'],
    gradesEn: ['Pre-Master Courses', 'Master Thesis', 'PhD Candidate']
  },
  { 
    id: 'self', 
    title: '💻 كورس / تعلم حر وتطوير ذاتي', 
    titleAr: '💻 كورس / تعلم حر وتطوير ذاتي', 
    titleEn: '💻 Self-Learning / Online Courses',
    emoji: '💻', 
    grades: ['برمجة وتطوير', 'لغات ومحادثة', 'تصميم وتسويق'],
    gradesAr: ['برمجة وتطوير', 'لغات ومحادثة', 'تصميم وتسويق'],
    gradesEn: ['Software Dev & Coding', 'Foreign Languages', 'Design & Marketing']
  },
];

export const HIGH_SCHOOL_TRACKS = [
  { id: 'science_bio', name: '🔬 علمي علوم (أحياء وطب)' },
  { id: 'science_math', name: '📐 علمي رياضة (هندسة وحاسبات)' },
  { id: 'arts', name: '📚 أدبي (علوم إنسانية ولغات)' },
  { id: 'azhar', name: '🕌 ثانوية أزهرية (علمي / أدبي)' },
  { id: 'bac_exp', name: '🧪 علوم تجريبية (بكالوريا)' },
  { id: 'bac_math', name: '🔢 علوم رياضية (بكالوريا)' },
  { id: 'bac_arts', name: '📜 آداب وعلوم إنسانية / اقتصاد (بكالوريا)' },
  { id: 'bac_tech', name: '⚙️ علوم تكنولوجية / مهنية (بكالوريا)' },
  { id: 'stem', name: '💻 مدارس المتفوقين (STEM)' },
];

export interface PresetCityItem {
  city: string;
  country: string;
  nameAr: string;
  countryAr: string;
  flag: string;
  defaultMethod: number;
}

export const PRESET_CITIES: PresetCityItem[] = [
  // 🇪🇬 مصر (Egypt)
  { city: 'Cairo', country: 'Egypt', nameAr: 'القاهرة', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Mansoura', country: 'Egypt', nameAr: 'المنصورة', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Alexandria', country: 'Egypt', nameAr: 'الإسكندرية', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Giza', country: 'Egypt', nameAr: 'الجيزة', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Tanta', country: 'Egypt', nameAr: 'طنطا', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Zagazig', country: 'Egypt', nameAr: 'الزقازيق', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Asyut', country: 'Egypt', nameAr: 'أسيوط', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Aswan', country: 'Egypt', nameAr: 'أسوان', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Suez', country: 'Egypt', nameAr: 'السويس', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Port Said', country: 'Egypt', nameAr: 'بورسعيد', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },
  { city: 'Ismailia', country: 'Egypt', nameAr: 'الإسماعيلية', countryAr: 'مصر', flag: '🇪🇬', defaultMethod: 5 },

  // 🇸🇦 السعودية (Saudi Arabia)
  { city: 'Riyadh', country: 'Saudi Arabia', nameAr: 'الرياض', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Makkah', country: 'Saudi Arabia', nameAr: 'مكة المكرمة', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Madinah', country: 'Saudi Arabia', nameAr: 'المدينة المنورة', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Jeddah', country: 'Saudi Arabia', nameAr: 'جدة', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Dammam', country: 'Saudi Arabia', nameAr: 'الدمام', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Khobar', country: 'Saudi Arabia', nameAr: 'الخبر', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Abha', country: 'Saudi Arabia', nameAr: 'أبها', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },
  { city: 'Tabuk', country: 'Saudi Arabia', nameAr: 'تبوك', countryAr: 'السعودية', flag: '🇸🇦', defaultMethod: 4 },

  // 🇦🇪 الإمارات (UAE)
  { city: 'Dubai', country: 'United Arab Emirates', nameAr: 'دبي', countryAr: 'الإمارات', flag: '🇦🇪', defaultMethod: 4 },
  { city: 'Abu Dhabi', country: 'United Arab Emirates', nameAr: 'أبوظبي', countryAr: 'الإمارات', flag: '🇦🇪', defaultMethod: 4 },
  { city: 'Sharjah', country: 'United Arab Emirates', nameAr: 'الشارقة', countryAr: 'الإمارات', flag: '🇦🇪', defaultMethod: 4 },

  // 🇯🇴 الأردن (Jordan)
  { city: 'Amman', country: 'Jordan', nameAr: 'عمان', countryAr: 'الأردن', flag: '🇯🇴', defaultMethod: 5 },
  { city: 'Irbid', country: 'Jordan', nameAr: 'إربد', countryAr: 'الأردن', flag: '🇯🇴', defaultMethod: 5 },
  { city: 'Zarqa', country: 'Jordan', nameAr: 'الزرقاء', countryAr: 'الأردن', flag: '🇯🇴', defaultMethod: 5 },

  // 🇰🇼 الكويت (Kuwait)
  { city: 'Kuwait City', country: 'Kuwait', nameAr: 'الكويت', countryAr: 'الكويت', flag: '🇰🇼', defaultMethod: 4 },

  // 🇮🇶 العراق (Iraq)
  { city: 'Baghdad', country: 'Iraq', nameAr: 'بغداد', countryAr: 'العراق', flag: '🇮🇶', defaultMethod: 3 },
  { city: 'Erbil', country: 'Iraq', nameAr: 'أربيل', countryAr: 'العراق', flag: '🇮🇶', defaultMethod: 3 },

  // 🇲🇦 المغرب العربي (North Africa)
  { city: 'Tunis', country: 'Tunisia', nameAr: 'تونس', countryAr: 'تونس', flag: '🇹🇳', defaultMethod: 3 },
  { city: 'Algiers', country: 'Algeria', nameAr: 'الجزائر', countryAr: 'الجزائر', flag: '🇩🇿', defaultMethod: 3 },
  { city: 'Rabat', country: 'Morocco', nameAr: 'الرباط', countryAr: 'المغرب', flag: '🇲🇦', defaultMethod: 3 },
  { city: 'Casablanca', country: 'Morocco', nameAr: 'الدار البيضاء', countryAr: 'المغرب', flag: '🇲🇦', defaultMethod: 3 },

  // 🇹🇷 تركيا والدول الغربية
  { city: 'Istanbul', country: 'Turkey', nameAr: 'إسطنبول', countryAr: 'تركيا', flag: '🇹🇷', defaultMethod: 13 },
  { city: 'London', country: 'United Kingdom', nameAr: 'لندن', countryAr: 'المملكة المتحدة', flag: '🇬🇧', defaultMethod: 3 },
  { city: 'Paris', country: 'France', nameAr: 'باريس', countryAr: 'فرنسا', flag: '🇫🇷', defaultMethod: 12 },
  { city: 'New York', country: 'United States', nameAr: 'نيويورك', countryAr: 'أمريكا', flag: '🇺🇸', defaultMethod: 2 },
];

export const COUNTRY_FLAG_MAP: Record<string, { ar: string; flag: string }> = {
  Egypt: { ar: 'مصر', flag: '🇪🇬' },
  'Saudi Arabia': { ar: 'السعودية', flag: '🇸🇦' },
  'United Arab Emirates': { ar: 'الإمارات', flag: '🇦🇪' },
  Jordan: { ar: 'الأردن', flag: '🇯🇴' },
  Kuwait: { ar: 'الكويت', flag: '🇰🇼' },
  Iraq: { ar: 'العراق', flag: '🇮🇶' },
  Tunisia: { ar: 'تونس', flag: '🇹🇳' },
  Algeria: { ar: 'الجزائر', flag: '🇩🇿' },
  Morocco: { ar: 'المغرب', flag: '🇲🇦' },
  Turkey: { ar: 'تركيا', flag: '🇹🇷' },
  'United Kingdom': { ar: 'المملكة المتحدة', flag: '🇬🇧' },
  France: { ar: 'فرنسا', flag: '🇫🇷' },
  'United States': { ar: 'أمريكا', flag: '🇺🇸' },
};

export const CALCULATION_METHODS = [
  { id: 5, nameAr: 'الهيئة المصرية العامة للمساحة (مصر والشام)' },
  { id: 4, nameAr: 'جامعة أم القرى بمكة المكرمة (السعودية والخليج)' },
  { id: 3, nameAr: 'رابطة العالم الإسلامي (عام)' },
  { id: 2, nameAr: 'الجمعية الإسلامية لشمال أمريكا (ISNA)' },
  { id: 1, nameAr: 'جامعة العلوم الإسلامية بكراتشي' },
  { id: 8, nameAr: 'منطقة الخليج العربي' },
  { id: 13, nameAr: 'رئاسة الشؤون الدينية التركية (Diyanet)' },
];

export const DEFAULT_PROFILE: UserProfile = {
  name: 'محمد إسماعيل',
  title: 'طالب متميز',
  bio: 'لا تؤجل عمل اليوم إلى الغد.. بالجد والاجتهاد نصل إلى القمة!',
  dreamGoal: 'التفوق والامتياز مع مرتبة الشرف',
  schoolOrUniversity: 'جامعة القاهرة — هندسة وحاسبات',
  targetGPA: 'امتياز (A+)',
  avatarType: 'emoji',
  avatarValue: '🎓',
  onboarded: true,
  xpPoints: 0,
  streakDays: 1,
  level: 1,
};

export const INITIAL_LESSONS: Lesson[] = [
  {
    id: 'lesson-1',
    subject: 'الفيزياء',
    teacher: 'أستاذ المادة',
    type: 'onsite',
    location: 'قاعة المحاضرات',
    startTime: '09:00',
    endTime: '10:30',
    days: [0, 2, 4], // Sun, Tue, Thu
    color: 'indigo',
    notes: 'تحضير مراجعة الدرس السابق',
  },
  {
    id: 'lesson-2',
    subject: 'الرياضيات',
    teacher: 'أستاذ المادة',
    type: 'online',
    link: 'https://zoom.us/j/123456789',
    startTime: '11:00',
    endTime: '12:30',
    days: [0, 1, 3], // Sun, Mon, Wed
    color: 'emerald',
    notes: 'حل نماذج وتدريبات',
  },
  {
    id: 'lesson-3',
    subject: 'اللغة الإنجليزية',
    teacher: 'أستاذ المادة',
    type: 'onsite',
    location: 'المعمل الرئيسي',
    startTime: '13:30',
    endTime: '15:00',
    days: [1, 3], // Mon, Wed
    color: 'amber',
  },
];

export const INITIAL_TASKS: StudentTask[] = [
  {
    id: 'task-1',
    title: 'حل تدريبات ونماذج مادة الفيزياء',
    description: 'مراجعة الأسئلة وتلخيص القوانين المهمة',
    subjectName: 'الفيزياء',
    dueDate: getTodayDateString(),
    dueTime: '20:00',
    priority: 'high',
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'واجب وتمارين الرياضيات المقررة',
    description: 'حل تدريبات الوحدة الأولى',
    subjectName: 'الرياضيات',
    dueDate: getTodayDateString(),
    dueTime: '22:00',
    priority: 'medium',
    completed: false,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_BADGES: BadgeItem[] = [
  {
    id: 'fajr-hero',
    titleAr: 'وسام فجر الإنجاز',
    titleEn: 'Fajr Scholar Medal',
    descriptionAr: 'أداء صلاة الفجر في موعدها والاستيقاظ الباكر للدراسة',
    descriptionEn: 'Perform Fajr prayer on time and start early',
    icon: 'Sunrise',
    category: 'prayers',
    xpReward: 200,
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'focus-beast',
    titleAr: 'وسام التركيز العميق',
    titleEn: 'Deep Focus Master',
    descriptionAr: 'إنهاء 10 جلسات مذاكرة بنظام التركيز المكثف',
    descriptionEn: 'Complete 10 focused study sessions',
    icon: 'Zap',
    category: 'study',
    xpReward: 200,
    requiredCount: 10,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'backlog-slayer',
    titleAr: 'وسام منجز الواجبات',
    titleEn: 'Assignments Finisher',
    descriptionAr: 'إنهاء 15 مهمة وواجب في موعدها المحدد',
    descriptionEn: 'Finish 15 tasks before due date',
    icon: 'CheckCircle2',
    category: 'tasks',
    xpReward: 250,
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'streak-legend',
    titleAr: 'وسام الاستمرارية والمواظبة',
    titleEn: 'Consistency & Streak Medal',
    descriptionAr: 'الحفاظ على تتابع دراسي متواصل لمدة 7 أيام',
    descriptionEn: 'Maintain a 7-day study streak',
    icon: 'Flame',
    category: 'streak',
    xpReward: 300,
    requiredCount: 7,
    currentCount: 1,
    isUnlocked: false,
  },
  {
    id: 'streak-titan',
    titleAr: 'وسام عملاق التتابع الأكاديمي',
    titleEn: 'Academic Streak Titan',
    descriptionAr: 'الوصول إلى 14 يوماً من المذاكرة المتواصلة',
    descriptionEn: 'Reach a 14-day study streak',
    icon: 'Star',
    category: 'streak',
    xpReward: 600,
    requiredCount: 14,
    currentCount: 1,
    isUnlocked: false,
  },
  {
    id: 'prayer-guardian',
    titleAr: 'حارس الفروض 🕌',
    titleEn: 'Prayer Guardian 🕌',
    descriptionAr: 'أداء 25 صلاة في وقتها المحدد',
    descriptionEn: 'Pray 25 daily prayers on time',
    icon: '🕌',
    category: 'prayers',
    xpReward: 350,
    requiredCount: 25,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'prayer-titan',
    titleAr: 'منارة الإيمان 🕋',
    titleEn: 'Pillar of Faith 🕋',
    descriptionAr: 'أداء 50 صلاة في وقتها مع الأذكار',
    descriptionEn: 'Log 50 prayers on time with Athkar',
    icon: '🕋',
    category: 'prayers',
    xpReward: 750,
    requiredCount: 50,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'note-master',
    titleAr: 'الموسوعة الدراسية 📝',
    titleEn: 'Knowledge Archivist 📝',
    descriptionAr: 'كتابة وتثبيت 5 ملخصات دراسية ذكية',
    descriptionEn: 'Write and pin 5 study notes',
    icon: '📝',
    category: 'study',
    xpReward: 150,
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'tasbeeh-100',
    titleAr: 'ذاكر الله 📿',
    titleEn: 'Tasbeeh Devotee 📿',
    descriptionAr: 'الوصول إلى 100 تسبيحة بالسبحة الإلكترونية',
    descriptionEn: 'Reach 100 counts on Digital Tasbeeh',
    icon: '📿',
    category: 'mastery',
    xpReward: 100,
    requiredCount: 100,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'tasbeeh-1000',
    titleAr: 'مسبّح الألفية 💎',
    titleEn: 'Millennium Tasbeeh 💎',
    descriptionAr: 'الوصول إلى 1,000 تسبيحة بالسبحة الذكية',
    descriptionEn: 'Reach 1,000 lifetime Tasbeeh counts',
    icon: '💎',
    category: 'mastery',
    xpReward: 500,
    requiredCount: 1000,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'quran-reader',
    titleAr: 'حافظ الورد القرآني 📖',
    titleEn: 'Quran Devotee 📖',
    descriptionAr: 'تسجيل قراءة 20 صفحة من القرآن الكريم',
    descriptionEn: 'Log 20 Quran pages read',
    icon: '📖',
    category: 'prayers',
    xpReward: 400,
    requiredCount: 20,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'excellence-star',
    titleAr: 'رائد الامتياز 🌟',
    titleEn: 'Excellence Pioneer 🌟',
    descriptionAr: 'تجميع 1000 نقطة خبرة (XP) والتفوق العام',
    descriptionEn: 'Accumulate 1000 total XP points',
    icon: '🌟',
    category: 'mastery',
    xpReward: 500,
    requiredCount: 1000,
    currentCount: 0,
    isUnlocked: false,
  },
  {
    id: 'grand-master',
    titleAr: 'أسطورة يسطا ذاكر 👑',
    titleEn: 'Yasta Zakir Legend 👑',
    descriptionAr: 'الوصول إلى 3000 نقطة خبرة والقمة الدراسية',
    descriptionEn: 'Accumulate 3000 total XP points',
    icon: '👑',
    category: 'mastery',
    xpReward: 1000,
    requiredCount: 3000,
    currentCount: 0,
    isUnlocked: false,
  }
];

export const ATHKAR_DATA = {
  study: [
    {
      id: 's1',
      title: 'دعاء بداية المذاكرة',
      titleEn: 'Study Commencement Prayer 📖',
      text: 'اللهم إني أسألك فهم النبيين، وحفظ المرسلين، والملائكة المقربين. اللهم اجعل ألسنتنا عامرة بذكرك، وقلوبنا بخشيتك، وأسرارنا بطاعتك.',
      textEn: 'O Allah, I ask You for the understanding of the prophets, the memory of the messengers, and the proximity of the angels. Fill our tongues with Your remembrance and hearts with Your reverence.',
      benefit: 'لصفاء الذهن وسرعة الاستيعاب وتوفيق الفهم',
      benefitEn: 'For mental clarity, swift comprehension, and blessing in study',
      count: 1,
    },
    {
      id: 's2',
      title: 'دعاء تيسير الصعب وتسهيل الفهم',
      titleEn: 'Prayer for Overcoming Hard Topics 🧠',
      text: 'اللهم لا سهل إلا ما جعلته سهلاً، وأنت تجعل الحزن إذا شئت سهلاً.',
      textEn: 'O Allah, nothing is easy except what You make easy, and You can make difficulty easy if You will.',
      benefit: 'يقال عند مواجهة مسألة أو درس معقد',
      benefitEn: 'Recited when encountering complex problems or difficult chapters',
      count: 3,
    },
    {
      id: 's3',
      title: 'دعاء تثبيت الحفظ والاسترجاع',
      titleEn: 'Prayer for Memory Retention 💡',
      text: 'اللهم إني أستودعك ما قرأت وما حفظت وما تعلمت، فرده عند حاجتي إليه، إنك على كل شيء قدير.',
      textEn: 'O Allah, I entrust to You what I have read, memorized, and learned, so return it to me when I need it most.',
      benefit: 'يقال عند ختام جلسة المذاكرة لحفظ المعلومات',
      benefitEn: 'Recited at the end of study sessions for long-term retention',
      count: 1,
    },
    {
      id: 's4',
      title: 'دعاء دخول قاعة الامتحان',
      titleEn: 'Exam Hall Entry Prayer 🎯',
      text: 'رب أدخلني مدخل صدق وأخرجني مخرج صدق واجعل لي من لدنك سلطاناً نصيراً.',
      textEn: 'My Lord, cause me to enter a sound entrance and to exit a sound exit and grant me from Yourself a supporting authority.',
      benefit: 'للسكينة والطمأنينة والتوفيق والتثبيت',
      benefitEn: 'For inner peace, confidence, and steadfast performance',
      count: 1,
    },
    {
      id: 's5',
      title: 'دعاء النسيان أو تعثر الإجابة',
      titleEn: 'Prayer for Recalling Forgotten Answers 🔍',
      text: 'يا جامع الناس ليوم لا ريب فيه، اجمع بيني وبين ضالتي ومعلوماتي.',
      textEn: 'O Gatherer of mankind on a Day about which there is no doubt, gather between me and the information I seek.',
      benefit: 'يقال عند استحضار معلومة تائهة',
      benefitEn: 'Recited when trying to recall an elusive concept during tests',
      count: 3,
    },
    {
      id: 's6',
      title: 'دعاء التوكل وانشراح الصدر',
      titleEn: 'Prayer for Eloquence & Relief 🌟',
      text: 'رب اشرح لي صدري ويسر لي أمري واحلل عقدة من لساني يفقهوا قولي.',
      textEn: 'My Lord, expand for me my chest, ease for me my task, and untie the knot from my tongue that they may understand my speech.',
      benefit: 'لطلاقة اللسان وسلاسة التعبير في الامتحانات والشفوي',
      benefitEn: 'For smooth articulation in oral exams and presentations',
      count: 3,
    },
  ],
  morning: [
    {
      id: 'm1',
      title: 'سيد الاستغفار',
      titleEn: 'Chief of Prayers for Forgiveness (Sayyid al-Istighfar) 🌅',
      text: 'اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك عليّ وأبوء بذنبي فاغفر لي فإنه لا يغفر الذنوب إلا أنت.',
      textEn: 'O Allah, You are my Lord, there is no god but You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can...',
      benefit: 'من قاله موقناً به ومات دخل الجنة',
      benefitEn: 'The most comprehensive morning supplication for peace and forgiveness',
      count: 1,
    },
    {
      id: 'm2',
      title: 'آية الكرسي',
      titleEn: 'Ayat Al-Kursi (The Throne Verse) 🕋',
      text: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ...',
      textEn: 'Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep...',
      benefit: 'حفظ من كل شر وحصن للمسلم',
      benefitEn: 'Divine protection and fortress for the entire day',
      count: 1,
    },
    {
      id: 'm3',
      title: 'رضيت بالله رباً',
      titleEn: 'Pleased with Allah as my Lord 🤲',
      text: 'رضيتُ بالله رباً، وبالإسلام ديناً، وبمحمدٍ صلى الله عليه وسلم نبياً.',
      textEn: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (pbuh) as my Prophet.',
      benefit: 'وجبت له الجنة ورضي الله عنه',
      benefitEn: 'Guarantees contentment and divine pleasure',
      count: 3,
    },
    {
      id: 'm4',
      title: 'بسم الله الذي لا يضر',
      titleEn: 'In the Name of Allah with Whose Name Nothing Harms 🛡️',
      text: 'بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم.',
      textEn: 'In the Name of Allah, with Whose Name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.',
      benefit: 'لم يضره شيء طوال اليوم',
      benefitEn: 'Complete safeguard from any harm or misfortune',
      count: 3,
    },
    {
      id: 'm5',
      title: 'يا حي يا قيوم برحمتك أستغيث',
      titleEn: 'O Ever-Living, by Your Mercy I Seek Help 💫',
      text: 'يا حي يا قيوم برحمتك أستغيث، أصلح لي شأني كله ولا تكلني إلى نفسي طرفة عين.',
      textEn: 'O Ever-Living, O Sustainer, by Your mercy I seek assistance; rectify all my affairs and leave me not to myself for the blink of an eye.',
      benefit: 'تيسير كل أمور اليوم والتوكل على الله',
      benefitEn: 'Total alignment and ease for all of today’s tasks',
      count: 3,
    },
  ],
  evening: [
    {
      id: 'e1',
      title: 'أمسينا وأمسى الملك لله',
      titleEn: 'We have reached the evening and dominion belongs to Allah 🌙',
      text: 'أمسينا وأمسى الملك لله والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.',
      textEn: 'We have reached the evening and all dominion belongs to Allah. Praise be to Allah; there is no deity but Allah alone with no partner.',
      benefit: 'شكر النعم وحفظ المساء',
      benefitEn: 'Gratitude for daily blessings and evening tranquility',
      count: 1,
    },
    {
      id: 'e2',
      title: 'أعوذ بكلمات الله التامات',
      titleEn: 'I Seek Refuge in the Perfect Words of Allah 🌌',
      text: 'أعوذ بكلمات الله التامات من شر ما خلق.',
      textEn: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      benefit: 'حماية من كل مكروه وضر في الليل',
      benefitEn: 'Protection from all evils throughout the night',
      count: 3,
    },
    {
      id: 'e3',
      title: 'الصلاة على النبي ﷺ',
      titleEn: 'Blessings upon the Prophet ﷺ 🕊️',
      text: 'اللهم صلِّ وسلم وبارك على نبينا محمد وعلى آله وصحبه أجمعين.',
      textEn: 'O Allah, send Your peace, blessings, and grace upon our Prophet Muhammad and upon his family and companions.',
      benefit: 'كفاية الهم وغفران الذنب ونيل الشفاعة',
      benefitEn: 'Relief of anxieties and multiplying rewards',
      count: 10,
    },
    {
      id: 'e4',
      title: 'حسبي الله لا إله إلا هو',
      titleEn: 'Allah is Sufficient for Me 🌸',
      text: 'حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم.',
      textEn: 'Allah is sufficient for me. There is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne.',
      benefit: 'كفاه الله ما أهمه من أمر الدنيا والآخرة',
      benefitEn: 'Sufficiency in all worldly and spiritual concerns',
      count: 7,
    },
  ],
  postPrayer: [
    {
      id: 'p1',
      title: 'الاستغفار بعد السلام',
      titleEn: 'Seeking Forgiveness Post-Prayer 🕌',
      text: 'أستغفر الله، أستغفر الله، أستغفر الله. اللهم أنت السلام ومنك السلام، تباركت يا ذا الجلال والإكرام.',
      textEn: 'I seek the forgiveness of Allah (x3). O Allah, You are Peace and from You comes peace. Blessed are You, Owner of Majesty and Honor.',
      benefit: 'سنة النبي ﷺ بعد كل صلاة مكتوبة',
      benefitEn: 'Prophetic Sunnah after concluding obligatory prayers',
      count: 3,
    },
    {
      id: 'p2',
      title: 'التسبيح والتحميد والتكبير',
      titleEn: 'Glorification, Praise & Takbeer (33x) 📿',
      text: 'سبحان الله (33)، الحمد لله (33)، الله أكبر (33)، تمام المائة: لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.',
      textEn: 'SubhanAllah (33x), Alhamdulillah (33x), Allahu Akbar (33x), concluding with: La ilaha illa Allah wahdahu la shareeka lah...',
      benefit: 'غفرت خطاياه وإن كانت مثل زبد البحر',
      benefitEn: 'Forgiveness of all minor sins and elevated rank',
      count: 33,
    },
  ],
  sleep: [
    {
      id: 'sl1',
      title: 'باسمك ربي وضعت جنبي',
      titleEn: 'In Your Name, My Lord, I Lie Down 🛌',
      text: 'باسمك ربي وضعت جنبي وبك أرفعه، فإن أمسكت نفسي فارحمها، وإن أرسلتها فاحفظها بما تحفظ به عبادك الصالحين.',
      textEn: 'In Your name my Lord I lie down, and in Your name I arise. If You take my soul then have mercy upon it, and if You return it then protect it...',
      benefit: 'حفظ الروح والنوم الهادئ والمريح',
      benefitEn: 'For deep, restorative, protected sleep and sweet dreams',
      count: 1,
    },
    {
      id: 'sl2',
      title: 'المعوذات والإخلاص',
      titleEn: 'The Three Protective Surahs (Ikhlas, Falaq, Nas) 🛡️',
      text: 'قراءة سورة الإخلاص، الفلق، والناس والنفث في الكفين ومسح الجسد.',
      textEn: 'Reciting Surah Al-Ikhlas, Al-Falaq, and An-Nas, gently blowing into the cupped hands, and wiping over the body.',
      benefit: 'سنة النبي ﷺ قبل النوم للوقاية والسكينة',
      benefitEn: 'Prophetic bedtime protection for body and mind',
      count: 3,
    },
  ],
};

